### ISSUE TITLE
Selected text is barely seen when the diffs, merge conflicts are highlighted

### ISSUE THREAD

**Issue by bencelaszlo** [sainnhe/gruvbox-material-vscode#1]
I use the 'Hard' option. When I select a text which is marked as a diff or merge conflict by Git.

**Comment by sainnhe** [comment]
Please try the master branch to see if you are satisfied with it.

Steps:

1. clone this repo
2. open it using vscode
3. press `F5`

**Comment by bencelaszlo** [comment]
Selection in diffs seems to be okay now, but it works weirdly in conflict areas.
![gruvbox](https://user-images.githubusercontent.com/19412564/64128737-58dbff00-cdb8-11e9-8c7b-0d298398bb1e.gif)

**Comment by sainnhe** [comment]
Sorry for late reply, I'm busy with light version of this theme recently.

I've tried this but can't reproduce this

![foo](https://user-images.githubusercontent.com/37491630/64219558-83cd6c80-cef8-11e9-82d4-b10c16ae4ff2.png)

I have no idea where the yellow background came from, could you provide steps to reproduce this?

**Comment by bencelaszlo** [comment]
1. Open a conflicted file.
2. Point to a character in the conflict area an move the cursor "backwards" (to left and up).

VS Code version: 1.3.7
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.11-arch1-1-ARCH

**Comment by bencelaszlo** [comment]
BTW I reloaded the VS Code now (the extension required that), and it is working as intended now. Thank you.

**Comment by sainnhe** [comment]
That's fine.
