### ISSUE TITLE
Theme is not available on VS Code Web

### ISSUE THREAD

**Issue by ronakg** [sainnhe/gruvbox-material-vscode#109]
Gruvbox Material theme is not available on VS Code Web.

![image](https://user-images.githubusercontent.com/1058322/129276616-d0836bc2-94e8-44d0-b402-984dc7efb674.png)

Go to https://github.dev/sainnhe/gruvbox-material-vscode to launch this repo in VS Code Web and try to install the Gruvbox Material theme.

**Comment by sainnhe** [comment]
This theme will regenerate /theme/gruvbox-material-*.json when user settings change, so it needs to access to local extension files.

Such extensions are restricted on vscode web, this is a mandatory mechanism set by Microsoft, I can't fix it.

**Comment by sainnhe** [comment]
Looks like it's possible

https://github.com/Binaryify/OneDark-Pro/pull/601

**Comment by sainnhe** [comment]
Now it should be available on vscode web, but the configuration options are not available yet due to the reason I mentioned above.
