### ISSUE TITLE
All versions not available under Linux

### ISSUE THREAD

**Issue by pyrsmk** [sainnhe/gruvbox-material-vscode#13]
First of all, thanks for this great extension. The themes are really balanced and comfortable for the eye.

Nevertheless, contrary to what I have on Mac, on Ubuntu I only have `Gruvbox material dark` and `Gruvbox material light` versions available.

I hope this could be a simple fix :)

**Comment by sainnhe** [comment]
That means this extension on your Mac has not been updated. In the newest version, there are only 2 variants available: `Gruvbox Material Dark` and `Gruvbox Material Light`.

But you can customize these 2 variants via user setting. See [customization](https://github.com/sainnhe/gruvbox-material-vscode#customization) in README.

**Comment by pyrsmk** [comment]
Indeed. So there's an issue with the installed version on Mac. Because I installed your theme a few days ago and I'm on `4.2.1`. There's no further version proposed by VSCode.

**Comment by pyrsmk** [comment]
Problem solved : my vscode app was not up-to-date.
