### ISSUE TITLE
Color for comment gutter

### ISSUE THREAD

**Issue by antfu** [sainnhe/gruvbox-material-vscode#16]
Comment gutters are used for VS Code's comment API, which you can see an application with https://github.com/vsls-contrib/codetour

The theme documents are described in the last section of [Editor Colors](https://code.visualstudio.com/api/references/theme-color#editor-colors)

![image](https://user-images.githubusercontent.com/11247099/79823444-6fc27680-83c6-11ea-96a5-b85c70c04864.png)

It will be nice if you could support that and make it less eye-catching. Thanks!

PS. I really appreciate the theme you made! Do you accept any donation?

**Comment by sainnhe** [comment]
Done via 199890d.

Thanks for your appreciation :)

Sorry but I don't accept any donation. If you find this project helpful, you can contribute code instead.

**Comment by antfu** [comment]
Thanks! But 6.1.4 doesn't seem to be live on the marketplace...

**Comment by sainnhe** [comment]
The newest version is `v6.1.3` instead of `v6.1.4`, it's already available on the marketplace.

**Comment by antfu** [comment]
My bad. Can confirm now. Thanks for the awesome work!
