### ISSUE TITLE
[Feature Request] More contrast for list selections

### ISSUE THREAD

**Issue by ronakg** [sainnhe/gruvbox-material-vscode#17]
Hi,

I really love this theme. I use it on both vscode and vim. Thanks for the great work.

For the vscode version, I find the contrast to be really low for list selections. For example, selected file in explorer, selected file in `Ctrl-tab` tab switcher, etc.

Is it possible to make these have more contrast so that we can easily identify what's selected? May be darker/lighter background or a border?

Example lists: 

<img width="612" alt="Screen Shot 2020-04-27 at 10 13 00 AM" src="https://user-images.githubusercontent.com/1058322/80400487-b9e8a380-886f-11ea-88f7-ecac16d389ed.png">

<img width="255" alt="Screen Shot 2020-04-27 at 10 11 07 AM" src="https://user-images.githubusercontent.com/1058322/80400286-6e35fa00-886f-11ea-8bda-9537a577ff30.png">

**Comment by sainnhe** [comment]
Done.

**Comment by ronakg** [comment]
Thanks. This is much better.
