### ISSUE TITLE
Incorrect syntax of .. in Ruby

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#18]
Hi, there is an issue with operator .. in Ruby language.
Include examples:
gruvbox material
![image](https://user-images.githubusercontent.com/58516282/80699467-aabe5b80-8ae4-11ea-9d83-396a994835fc.png)
dark+
![image](https://user-images.githubusercontent.com/58516282/80699495-b90c7780-8ae4-11ea-9d7b-7da1781a1ad5.png)

**Comment by sainnhe** [comment]
Should be fixed in e008c2d.

**Comment by Z4RX** [comment]
Thx for very fast fix!
