### ISSUE TITLE
no syntax highlight on pug

### ISSUE THREAD

**Issue by yoyoys** [sainnhe/gruvbox-material-vscode#2]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/22124891/64939617-24764180-d894-11e9-977c-d6753d7461f7.png">

here's example output from aye mirage
<img width="552" alt="image" src="https://user-images.githubusercontent.com/22124891/64939663-51c2ef80-d894-11e9-8105-fa0dc167140f.png">

**Comment by sainnhe** [comment]
I've optimized pug with the same syntax highlighting logic as css. You can now update this extension and see if you are satisfied with it.

**Comment by sainnhe** [comment]
Closed since I haven’t received a response for too long, and I personally think this problem has been solved.
