### ISSUE TITLE
cpp wrong string colors with colorful syntax

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#24]
It looks like a bug. Colorful syntax made cpp specifiers the same color as string text.
![cpp_issue](https://user-images.githubusercontent.com/58516282/85212055-aa5d7680-b357-11ea-9e70-ba77c558a574.png)

**Comment by Z4RX** [comment]
I think that strings should not be green as functions. It makes code less scanable and brokes logic of syntax highlighting.
I suggest to change it to color of numbers ( inspired by One Dark Pro) or change colors of strings and specifiers as in C lang files.

**Comment by Z4RX** [comment]
First draw
```
            {
                "scope": "constant.other.placeholder.cpp, constant.character.escape.cpp",
                "settings": {
                    "foreground": "#D3869B"
                }
            },
            {
                "scope": "string.quoted.other.lt-gt.include.cpp, string.quoted.double.include.cpp, string.quoted.double.cpp, string.quoted.single.cpp, punctuation.definition.string.begin.cpp, punctuation.definition.string.end.cpp",
                "settings": {
                    "foreground": "#D8A657"
                }
            },
            {
                "scope": "entity.name.type.cpp, entity.name.type.parameter.cpp, storage.type.built-in.cpp, storage.type.built-in.primitive.cpp",
                "settings": {
                    "foreground": "#E78A4E"
                }
            },
```

**Comment by sainnhe** [comment]
That's the one of the reasons why I decided to add a new syntax highlighting logic and set it as the default.

See discussion in #8 and #9.

I'd recommend you to disable colorful syntax instead.
