### ISSUE TITLE
Some files/folders aren't highlighted when hovered over

### ISSUE THREAD

**Issue by KyleErhabor** [sainnhe/gruvbox-material-vscode#240]
- Operating system/version: macOS Monterey (12.5)
- VSCode version: 1.70.0

### Settings

```json
{
  "workbench.colorTheme": "Gruvbox Material Dark",
  "gruvboxMaterial.darkContrast": "hard"
}
```

### Steps to reproduce this bug

1. Go to (file) Explorer (note this is applicable to Search as well)
2. Hover over files/folders

### Actual behaviour

"Marked" entries (git changes/ignored, problems, etc.) aren't highlighted when hovered over while "unmarked" entries are. Folder paths are underlined, so I assume Visual Studio Code's default behavior is being used.

https://user-images.githubusercontent.com/40676441/183739829-ee785577-72e2-46ba-ac6f-f125796555a0.mov

### Expected behaviour

Any entry hovered over would be highlighted. I don't know if this is a feature of Gruvbox, but it would be nice if it were an option.

**Comment by sainnhe** [comment]
Looks like vscode didn't provide tokens to customize such colors: https://code.visualstudio.com/api/references/theme-color

I'm not sure how to implement this, PR is welcome.
