### ISSUE TITLE
[Ruby] wrong arguments separator color in method definition

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#25]
method arguments separator work in progress

**Comment by Z4RX** [comment]
Separator of arguments list in method definition is not correct

here is example:
![rb](https://user-images.githubusercontent.com/58516282/85430605-022ef400-b589-11ea-832d-e918b02f6a51.png)

**Comment by Z4RX** [comment]
Looks like it is VS Code grammar issue, no one punctuation.separator change it's color.

**Comment by sainnhe** [comment]
I tried this code:

```typescript
    {
      name: "Ruby white",
      scope: "meta.function.method.with-arguments.ruby",
      settings: {
        foreground: palette.fg,
      },
    },
```

Looks like it can fix this bug. However, the scope is named as `meta.function.method.with-arguments.ruby` which means it refers to a method, so I don't if it can cause other problems.

By the way, I think it's not a good idea to organize all the issues related to ruby here, users should open a new issue if they encountered another problem.

**Comment by Z4RX** [comment]
Ok I see, i ll try to check this fix and find bugs

**Comment by Z4RX** [comment]
Looks like there are no issues with this fix

**Comment by sainnhe** [comment]
Fixed. A new version is available on the marketplace.
