### ISSUE TITLE
Proposal: Change whitespace render color to be more subtle

### ISSUE THREAD

**Issue by ronakg** [sainnhe/gruvbox-material-vscode#26]
Existing foreground color for `editorWhitespace` is same as that of comments. IMO it should be little less bright so that it's more subtle.

Current color:

<img width="453" alt="Screen Shot 2020-07-02 at 3 09 57 PM" src="https://user-images.githubusercontent.com/1058322/86413475-26b85980-bc76-11ea-81fa-88b908892881.png">

Proposed color: `#3c3836`

<img width="450" alt="Screen Shot 2020-07-02 at 3 09 40 PM" src="https://user-images.githubusercontent.com/1058322/86413471-23bd6900-bc76-11ea-85ff-3e03cb929705.png">

**Comment by sainnhe** [comment]
I think `#3c3836` is way too dark, maybe `#45403d` is better.

Done via bacb1e3, I'll release a new version later.

**Comment by sainnhe** [comment]
I've published a new version on marketplace, you can update this extension and get it a try.

**Comment by ronakg** [comment]
Thanks!
