### ISSUE TITLE
 Please publish the extension to Open VSX

### ISSUE THREAD

**Issue by eternal-sorrow** [sainnhe/gruvbox-material-vscode#29]
Hi!

I'm a VS Code-OSS user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.

I want to request if it's possible to add the Gruvbox Material extension on the [open-vsx.org](https://open-vsx.org/) marketplace, because it's unclear if Microsoft marketplace is legal to use on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

Thanks.

**Comment by sainnhe** [comment]
Thank you for this info!

I've published this extension on ovsx, see [here](https://open-vsx.org/extension/sainnhe/gruvbox-material).

However, I can't figure out how to use open-vsx.org, could you help me complete the installation guide? 5ad5be4

**Comment by eternal-sorrow** [comment]
The same way as with M$ marketplace, if your VS Code build includes Open-VSX instead of it. It should be possible to edit the `product.json` of an existing VS Code installation and set the extension gallery to open-vsx like shis:
```
  "extensionsGallery": {
    "serviceUrl": "https://open-vsx.org/vscode/gallery",
    "itemUrl": "https://open-vsx.org/vscode/item"
  },
```

**Comment by eternal-sorrow** [comment]
I don't know if `product.json` will be overwritten with vscode update.

**Comment by sainnhe** [comment]
Done. The readme has been updated and a new version is available on both vscode marketplace and open vsx registry.
