### ISSUE TITLE
Gutter colors for diff are too dark

### ISSUE THREAD

**Issue by batisteo** [sainnhe/gruvbox-material-vscode#3]
Markers in the gutter for diffs in the current file is way too dark to be visible.

![Screenshot from 2019-09-17 11-50-18](https://user-images.githubusercontent.com/2727048/65031548-b9834400-d941-11e9-895f-37b7bec31983.png)

![Screenshot from 2019-09-17 11-51-34](https://user-images.githubusercontent.com/2727048/65031552-bb4d0780-d941-11e9-940c-5a1711dc380f.png)

**Comment by sainnhe** [comment]
I've adjusted it, you can update this extension and get it a try.

**Comment by batisteo** [comment]
Awesome, this is much better!!
I really like this theme :+1:
