### ISSUE TITLE
[TODO] fix ruby hash syntax

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#31]
Now there is 2 ruby TS purple scopes. 1 of them should be italic other not.
Find a solution to separate them.

**Comment by sainnhe** [comment]
There's some problem in your development flow.

1. Please take a look at the commit comment. As what I said in 1821f8d, there is nothing wrong in the README.
2. Please do NOT push to master branch directly, you should fork this repo and submit commits by PR instead.
3. As what I said in previous issues, do not release new versions casually, remember that every time a new version is release, users will need to reload the window for 2 times.

**Comment by Z4RX** [comment]
1. I thought you just mistyped an extension
3. It was a fix of a really disgusting thing, so it was a necessary release
Here is an example
<img width="1440" alt="Снимок экрана 2020-07-31 в 18 05 20" src="https://user-images.githubusercontent.com/58516282/89048427-7c0c8700-d358-11ea-9446-9cc70c4dcbf3.png">

**Comment by sainnhe** [comment]
Sorry for my misunderstanding, looks like it is annoying indeed.

For the usage of git, you can have a look at [the book](https://git-scm.com/book/en/v2), it takes you for about 2-3 hours to complete reading.

Git is a distributed version control system, at least we should develop on different branchs, I think it's quite necessary to create your own branch/fork.

**Comment by Z4RX** [comment]
Thanks! Ok, no problem, next time I'll do a branch

**Comment by Z4RX** [comment]
![image](https://user-images.githubusercontent.com/58516282/89101543-71f69100-d409-11ea-96e6-84124e7ddec8.png)

@sainnhe does keyword name impact on the code or this change will work?

**Comment by sainnhe** [comment]
This should work. The "name" is used to distinguish between different scopes, you can name it as whatever you like.

**Comment by Z4RX** [comment]
Thanks, I'll create a branch with this change and test it, so in the next release we can deploy it.

**Comment by Z4RX** [comment]
I made 2 branches especially, `ruby-fixes` will collect a "package" of fixes and used a testing playground, don't include it to release pls till I do a pull request.
Branch related on this issue provide a strong modifications and it's already tested and ready for release.
