### ISSUE TITLE
Django templates syntax

### ISSUE THREAD

**Issue by Z4RX** [sainnhe/gruvbox-material-vscode#39]
@sainnhe I try to made a django templates syntax for [django ext](https://github.com/vscode-django/vscode-django). Here is a  [branch](https://github.com/sainnhe/gruvbox-material-vscode/tree/django-templates-syntax). Can you check it and probably optimize?

P.S.  Don't forget to make file associations.

**Comment by sainnhe** [comment]
Sorry but I may not have time recently, the past 3 weeks is my final vocation :(

I may come back in the end of December.

**Comment by Z4RX** [comment]
No problem, enjoy your vacation.

This branch will wait for you)

**Comment by sainnhe** [comment]
![demo](https://user-images.githubusercontent.com/37491630/103332673-e52e2d00-4aa5-11eb-9cf0-cd823e155e5a.png)

I just tried it and I think it works fine, do we need any optimization?

**Comment by Z4RX** [comment]
I think we can release it and fix some possible issues.
I have got covid, so it's possible that I'll absent this month

**Comment by sainnhe** [comment]
OMG, be safe! Wear a mask and go to the hospital as soon as possible.

Hope you can recover soon!
