### ISSUE TITLE
Readability of remote connection status on hover

### ISSUE THREAD

**Issue by tdy** [sainnhe/gruvbox-material-vscode#43]
- Operating system/version: Windows 10 Pro 19042.630
- Extension version: 6.3.4
- VSCode version:
    - Version: 1.51.1 (user setup)
    - Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
    - Date: 2020-11-10T23:34:32.027Z
    - Electron: 9.3.3
    - Chrome: 83.0.4103.122
    - Node.js: 12.14.1
    - V8: 8.3.110.13-electron.0
    - OS: Windows_NT x64 10.0.19042

### Settings

```json
"workbench.colorTheme": "Gruvbox Material Dark",
```

### Steps to reproduce this bug

Hover over the remote connection box in the bottom left.

### Actual behaviour

On hover, the fg text stays dark when the bg inverts to dark.

<img src="https://user-images.githubusercontent.com/2503508/100791214-87db8900-33de-11eb-8c87-dfd5abd00769.gif" width="400px">

### Expected behaviour

On hover, the fg text should invert to light when the bg goes dark.

**Comment by Z4RX** [comment]
Thanks for your feedback, I will fix it soon

**Comment by Z4RX** [comment]
@tdy I'm so sorry, got sudden troubles, so I am a bit busy now, but will fix this issue as soon as possible

**Comment by tdy** [comment]
@Z4RX no problem, take your time

**Comment by sainnhe** [comment]
Since vscode does not provide something like `statusBarItem.remoteHoverBackground`, I can't change the behavior when hover it.

So I simply use the black as the background color of this extension icon. IMO, this should be the preferred solution, because this can help you more focus on code.
