### ISSUE TITLE
punctuation.definition.string.begin/end

### ISSUE THREAD

**Issue by Liguma** [sainnhe/gruvbox-material-vscode#45]
Suggestion: make the `punctuation.definition.string.begin/end` to `"foreground": "#928374`

This makes it easier to distinguish the quotation marks from the rest of the `string`.

greeting,
Liguma

**Comment by sainnhe** [comment]
I think it's not a good idea.

Say we have bash script code like this:

```shell
printf "%s %s" "date: ${var1}" "location: ${var2}"
```

It will be hard to distinguish between these strings, especially when there are spaces inside each string.
