### ISSUE TITLE
Add settings to enable/disable background coloring for error/warning/info

### ISSUE THREAD

**Issue by cooperaustinj** [sainnhe/gruvbox-material-vscode#46]
Hi,

I noticed that the theme is now highlighting text that is part of an error/warning/info:

![image](https://user-images.githubusercontent.com/12889451/104997649-8c401d80-59ef-11eb-9ef1-34b63916e8c7.png)

I found this commit which seems to be the source: https://github.com/sainnhe/gruvbox-material-vscode/commit/76ca770015a76bf39d2bfce8b0c2ff5565330a29

Is it possible for these background color changes to be wrapped behind a setting that can be disabled?  I find the backgrounds quite distracting.

If a PR would be considered, I can also take a look at doing this - though I haven't worked on a VS Code extension/theme before.  I'd imagine I could figure it out.

**Comment by cooperaustinj** [comment]
Well, I found this closed issue.  https://github.com/sainnhe/gruvbox-material-vscode/issues/44

I guess this isn't something desirable.  I'm going with the "hack" then and closing this issue.

**Comment by sainnhe** [comment]
Looks like many users need this feature, I'll add it later.

**Comment by cooperaustinj** [comment]
I believe being able to set the color for each level and to disable the background entirely for each level would be the way to go.

**Comment by sainnhe** [comment]
Done in v6.3.6 .
