### ISSUE TITLE
Distinguish tab.activeForeground and tab.inactiveForeground

### ISSUE THREAD

**Issue by andodet** [sainnhe/gruvbox-material-vscode#47]
I think it would be a nice touch to better distinguish between `tab.activeForeground` and `tab.inactiveForeground` colors. I am used to work with multiple panels and this would visually aid to identify in which panel is the tab I am currently working on. 

Something in the lines of the settings below (or whatever you find more sensible) would be terrific:
```
"tab.activeForeground": "#ebdbb2",
"tab.inactiveForeground": "#a89984"
```
Let me know what you think about this.

### Credits
Found it in [this][1] gruvbox variation. 

[1]: https://github.com/jdinhify/vscode-theme-gruvbox

**Comment by sainnhe** [comment]
Try flat workbench style.
