### ISSUE TITLE
Where is 𝐃𝐚𝐫𝐤 𝐇𝐚𝐫𝐝 𝐅𝐥𝐚𝐭?

### ISSUE THREAD

**Issue by sgon00** [sainnhe/gruvbox-material-vscode#48]
I can see "𝐃𝐚𝐫𝐤 𝐇𝐚𝐫𝐝 𝐅𝐥𝐚𝐭" screenshot from the README. But after installation, I don't find such theme. How can I use it? Thanks a lot.

**Comment by sainnhe** [comment]
It's documented in [README](https://github.com/sainnhe/gruvbox-material-vscode#customization).
