### ISSUE TITLE
Icon for this extension

### ISSUE THREAD

**Issue by GulajavaMinistudio** [sainnhe/gruvbox-material-vscode#5]
Thank you for creating this theme. Im using it and love it.
But there's little detail that need soved. Give it icon so can be recognized in VS Code Marketplace or in VS Code Extension menu .

https://marketplace.visualstudio.com/items?itemName=sainnhe.gruvbox-material

**Comment by sainnhe** [comment]
Thanks for your suggestion. I will add an icon in the future.

**Comment by GulajavaMinistudio** [comment]
Can i contribute to give some icon design ? i have some idea about icon

**Comment by sainnhe** [comment]
Of course yes 😊

Thank you very much!

**Comment by GulajavaMinistudio** [comment]
Hello, i designed this icon for your extension icon. I made it with color palette from original gruvbox color palette. I can send you SVG file for this icon, for your customization .


![color-palette-pngs](https://user-images.githubusercontent.com/11639412/69912648-d4545780-145e-11ea-960f-9f6487403d8a.png)

**Comment by sainnhe** [comment]
Great work! 👍

Could you send the SVG file to my gmail: sainnhe@gmail.com

I'm a bit busy recently, I will add the new icon in a few days.

**Comment by GulajavaMinistudio** [comment]
Ok, i have send you email. Hope you check it in your Inbox :)

**Comment by sainnhe** [comment]
Thanks for your help! I'll add the icon later 😆

**Comment by sainnhe** [comment]
What do you think of this?

![](https://user-images.githubusercontent.com/37491630/69936608-3bcbdf00-1513-11ea-8711-96b3be149e1a.png)

**Comment by GulajavaMinistudio** [comment]
Well, it's OK and better suited with material palette. Im agree with that.  :smile:

**Comment by sainnhe** [comment]
I have added icon for this extension, and your contribution is mentioned in the README.

Thanks again for your help!

**Comment by sainnhe** [comment]
Oh, I just ignored a question. Since there may be color adjustments in the future and the icon may be changed, I want to add the svg file to this repository so that I can use git to manage it.

Do you mind if I open source it, or do I need to add a license for it?

**Comment by GulajavaMinistudio** [comment]
Dont worry, i open source this icon, so you can modify it freely. Happy create :smiley:

**Comment by sainnhe** [comment]
Thanks for your kind ;)
